matrix:
  include:
    - language: node_js
      node_js: 12
      sudo: required
      dist: trusty
      env:
        - NAME="Chrome"
      addons:
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable
      before_script:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - sleep 3 # give xvfb some time to start
      script: npm run test:ci:chrome
    - language: node_js
      node_js: 12
      sudo: required
      dist: trusty
      env:
        - NAME="Firefox"
      addons:
        firefox: latest
      before_script:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - sleep 3 # give xvfb some time to start
      script: npm run test:ci:firefox
